"use client";

import { useCallback, useEffect, useState } from "react";

import { getCanvas } from "@/lib/api";
import type { Canvas } from "@/lib/types";

import CanvasRenderer from "./CanvasRenderer";

// The "UI" half of the agent: the generative-UI panel beside the chat. It owns
// fetching the canvas by id and re-fetching when the agent updates it (the chat
// stream fires a fresh `canvasId`/`reloadKey` each time). `onAction` carries a
// button/form interaction back into the chat as the next message.
export default function CanvasPanel({
  canvasId,
  reloadKey,
  onClose,
  onAction,
}: {
  canvasId: string;
  reloadKey: number;
  onClose: () => void;
  onAction: (message: string) => void;
}) {
  const [canvas, setCanvas] = useState<Canvas | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    let cancelled = false;
    getCanvas(canvasId)
      .then((c) => {
        if (!cancelled) {
          setCanvas(c);
          setError(null);
        }
      })
      .catch(() => {
        if (!cancelled) setError("Couldn't load this canvas.");
      });
    return () => {
      cancelled = true;
    };
  }, [canvasId]);

  // Reload on a new canvas id or when the agent updates the same one.
  useEffect(() => load(), [load, reloadKey]);

  return (
    <div className="flex h-full min-h-0 flex-col rounded-xl border border-border bg-base">
      <div className="flex items-center justify-between gap-2 border-b border-border px-4 py-3">
        <div className="min-w-0">
          <div className="truncate text-[14px] font-semibold text-foreground">
            {canvas?.title ?? "Canvas"}
          </div>
          <div className="text-[11px] text-muted">Generated by your agent</div>
        </div>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close canvas"
          className="shrink-0 cursor-pointer rounded-md px-2 py-1 text-[16px] text-muted hover:bg-surface hover:text-foreground"
        >
          ×
        </button>
      </div>

      <div className="scroll-thin min-h-0 flex-1 overflow-y-auto p-4">
        {error ? (
          <div className="rounded-lg border border-error/30 bg-error/10 px-3 py-2 text-[12px] text-error">
            {error}
          </div>
        ) : canvas ? (
          <CanvasRenderer blocks={canvas.blocks} onAction={onAction} />
        ) : (
          <div className="text-[13px] text-muted">Loading…</div>
        )}
      </div>
    </div>
  );
}
