"use client";

import { useCallback, useEffect, useState } from "react";

import { ApiError, createTableRow, getCanvas } from "@/lib/api";
import type { Canvas, CanvasBlock } from "@/lib/types";

import CanvasRenderer, { type SubmitResult } from "./CanvasRenderer";

type FieldDef = { name: string; label?: string; column?: string };

// The "UI" half of the agent: the generative-UI panel beside the chat. It owns
// fetching the canvas by id and re-fetching when the agent updates it (the chat
// stream fires a fresh `canvasId`/`reloadKey` each time). `onAction` carries a
// button/form interaction back into the chat as the next message; a form bound
// to a `table_id` instead writes a row straight into that table.
export default function CanvasPanel({
  workspaceId,
  canvasId,
  reloadKey,
  onClose,
  onAction,
}: {
  workspaceId: string;
  canvasId: string;
  reloadKey: number;
  onClose: () => void;
  onAction: (message: string) => void;
}) {
  const [canvas, setCanvas] = useState<Canvas | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    let cancelled = false;
    getCanvas(canvasId)
      .then((c) => {
        if (!cancelled) {
          setCanvas(c);
          setError(null);
        }
      })
      .catch(() => {
        if (!cancelled) setError("Couldn't load this canvas.");
      });
    return () => {
      cancelled = true;
    };
  }, [canvasId]);

  // Reload on a new canvas id or when the agent updates the same one.
  useEffect(() => load(), [load, reloadKey]);

  // Form submit: a table-bound form writes a row; otherwise relay to the chat.
  // The row is keyed by column name — the backend resolves names to column ids
  // and coerces values, so the agent only needs the table id and column names.
  const handleSubmit = useCallback(
    async (block: CanvasBlock, values: Record<string, string>): Promise<SubmitResult> => {
      const tableId = typeof block.table_id === "string" ? block.table_id : null;
      if (!tableId) {
        const fields = Array.isArray(block.fields) ? (block.fields as FieldDef[]) : [];
        const parts = fields.map((f) => `${f.label || f.name}: ${values[f.name] ?? ""}`);
        const title = typeof block.title === "string" ? block.title : "Form";
        onAction(`${title} submitted — ${parts.join("; ")}`);
        return { ok: true, message: "Sent to agent" };
      }
      const fields = Array.isArray(block.fields) ? (block.fields as FieldDef[]) : [];
      const data: Record<string, string> = {};
      for (const f of fields) {
        const v = values[f.name];
        if (v === undefined || v === "") continue; // skip blanks; backend fills defaults
        data[f.column || f.label || f.name] = v;
      }
      try {
        await createTableRow(workspaceId, tableId, data);
        return { ok: true, message: "Added to table" };
      } catch (e) {
        return { ok: false, message: e instanceof ApiError ? e.message : "Couldn't save" };
      }
    },
    [workspaceId, onAction],
  );

  return (
    <div className="flex h-full min-h-0 flex-col rounded-xl border border-border bg-base">
      <div className="flex items-center justify-between gap-2 border-b border-border px-4 py-3">
        <div className="min-w-0">
          <div className="truncate text-[14px] font-semibold text-foreground">
            {canvas?.title ?? "Canvas"}
          </div>
          <div className="text-[11px] text-muted">Generated by your agent</div>
        </div>
        <button
          type="button"
          onClick={onClose}
          aria-label="Close canvas"
          className="shrink-0 cursor-pointer rounded-md px-2 py-1 text-[16px] text-muted hover:bg-surface hover:text-foreground"
        >
          ×
        </button>
      </div>

      <div className="scroll-thin min-h-0 flex-1 overflow-y-auto p-4">
        {error ? (
          <div className="rounded-lg border border-error/30 bg-error/10 px-3 py-2 text-[12px] text-error">
            {error}
          </div>
        ) : canvas ? (
          <CanvasRenderer blocks={canvas.blocks} onAction={onAction} onSubmit={handleSubmit} />
        ) : (
          <div className="text-[13px] text-muted">Loading…</div>
        )}
      </div>
    </div>
  );
}
